### PR TITLE
VM: Bump version of Ubuntu ISO image to 16.04.5

### PR DESCRIPTION
**Pull request by mkszuba**
It got released in late July 2018.

### CODE REVIEW

**Comment by tgrego** [comment]
We should do the jump to 18.04, but that is more work...

**Comment by lairdm** [comment]
It would be more work, but not a huuuge amount more work. But probably half a day to a day. The issue is the init string, the forced typing boxcutter pushes in to the boot loader. Now boxcutter probably has 18.04 installers that we could just switch to.

The second issue is the subtle changes to the distro. Things could break, such as "where do you put the wallpaper file" or "how do you keep the screen lock off", I experienced these when going frm 14 to 16. Again, not overwhelming, it just takes some googling to see how you configure these things via command line installer for the newer OS version.

**Comment by mkszuba** [comment]
Indeed, chances are it probably wouldn't be too much work to upgrade to 18.04. That said, isn't one of the advantages of sticking with Long Term Support versions that we do not *have to* upgrade to the next one as soon as it comes out (18.04 is just over 4 months old and hasn't received any point releases yet)? Xenial remains officially supported until April 2021.

Or is there something in Ensembl that doesn't work right under 16.04?

**Comment by nerdstrike** [comment]
The update to 18.04 can come in its own time. I see no reason not to merge this as is

**Comment by mkszuba** [comment]
Note on upgrading Ubuntu to 18.04: as of today, it doesn't work, the boxcutter template for this version (which is available in Git) fails interrupt the bootloader to pass the necessary boot arguments.

**Pull request merged**
